### ISSUE TITLE
'showfps' command fails when 'devconsole.dat' file is missing

### ISSUE THREAD

**Issue by samlletas** [DavidF-Dev/Unity-DeveloperConsole#3]
When running the command `showfps 1` and if  `devconsole.dat` file is missing the following exception is raised:

`
NullReferenceException: Object reference not set to an instance of an object
DavidFDev.DevConsole.DevConsoleMono.OnGUI () (at Library/PackageCache/com.davidfdev.devconsole@3d2a0ad071/Runtime/DevConsoleMono.cs:1409)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`

However, setting any other stat beforehand, for example `stats_set "test" 123` seems to prevent this error.

**Package version:** 1.04
**Unity version:** 2021.2.14

**Comment by DavidF-Dev** [comment]
Fixed in latest [release](https://github.com/DavidF-Dev/Unity-DeveloperConsole/releases/tag/1.0.5).

**Comment by samlletas** [comment]
Awesome, thanks!
